### ISSUE TITLE
Cataclysm

### ISSUE THREAD

**Issue by julianofischer** [npapanik/Adyton#10]
Hey, how are you?
Excuse me my ignorance, but what is "Cataclysm"  deletion mechanism?

Thank you.

**Comment by npapanik** [comment]
Hi Juliano,

"Cataclysm" is an ideal deletion mechanism that instantly deletes all replicas of a packet p (that exist across the network) when p reaches its destination. Of course, this mechanism exists only for evaluation purposes (best performing) since it is rather unrealistic. We have used it mainly to assess the performance of the other deletion mechanisms. 

I'll try to post some information regarding deletion mechanisms in our wiki page. In my opinion, the deletion mechanism has a significant impact on the performance of multi-copy protocols. However, it has received little attention so far. Most papers of the literature either use vaccine (which incurs high overhead) or a TTL-based mechanism (it is very hard to define the best TTL value) or not mention the deletion mechanism at all. 

Cheers!

**Comment by npapanik** [comment]
I've also opened a new issue (#11) regarding Vaccine's implementation that needs improvement.
